server:
  port: 8888
spring:
  cloud:
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
           - Path=/pms/**
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848